"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

from dotenv import load_dotenv
import os

load_dotenv()  # Automatically finds .env file
django_secret_key = os.getenv('DJANGO_SECRET_KEY')
openwebui_api_key = os.getenv('OPENWEBUI_API_KEY')
moodle_shared_secret = os.getenv('MOODLE_SHARED_SECRET')
moodle_consumer_key = os.getenv('MOODLE_CONSUMER_KEY')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = django_secret_key

PYLTI_CONFIG = {
    'consumers': {
        moodle_consumer_key: {
            'secret': moodle_shared_secret
        }
    }
}

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'lti_tool',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Allow Moodle to render Django inside an iFrame
X_FRAME_OPTIONS = 'ALLOWALL'
# Reverse proxy support for HTTPS + forwarded host in production.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
# Required when served in an iframe from Moodle.
SESSION_COOKIE_SAMESITE = os.getenv('SESSION_COOKIE_SAMESITE', 'None')
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'True').lower() == 'true'
CSRF_COOKIE_SAMESITE = os.getenv('CSRF_COOKIE_SAMESITE', 'None')
CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'True').lower() == 'true'

# LTI launch URL normalization behavior behind proxies.
LTI_TRUST_PROXY_HEADERS = os.getenv('LTI_TRUST_PROXY_HEADERS', 'False').lower() == 'true'
LTI_EXTERNAL_LAUNCH_URL = os.getenv('LTI_EXTERNAL_LAUNCH_URL', '')
LTI_SIGNATURE_DEBUG = os.getenv('LTI_SIGNATURE_DEBUG', 'False').lower() == 'true'

# Open WebUI API configuration
OPENWEBUI_API_KEY = openwebui_api_key
OPENWEBUI_URL = os.getenv('OPENWEBUI_URL', 'http://localhost:3000')
OPENWEBUI_TRUSTED_EMAIL_HEADER = os.getenv('OPENWEBUI_TRUSTED_EMAIL_HEADER', '')
OPENWEBUI_TRUSTED_NAME_HEADER = os.getenv('OPENWEBUI_TRUSTED_NAME_HEADER', '')
OPENWEBUI_TRUSTED_ROLE_HEADER = os.getenv('OPENWEBUI_TRUSTED_ROLE_HEADER', '')
OPENWEBUI_AUTOLOGIN_PASSWORD = os.getenv('OPENWEBUI_AUTOLOGIN_PASSWORD', '')
OPENWEBUI_DEFAULT_MODEL = os.getenv('OPENWEBUI_DEFAULT_MODEL', '')

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Force Django to generate internal URLs with /django prefix
FORCE_SCRIPT_NAME = '/django'

# Static files
STATIC_URL = '/django/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Media files
MEDIA_URL = '/django/media/'
MEDIA_ROOT = BASE_DIR / 'media'

